[workspace]
members = [
    "code/coding_problems",
    "code/first-word",
    "notes/packages-crates-modules/snippets/thela",
    "notes/packages-crates-modules/snippets/algos",
    "projects/guessing_game",
]
resolver = "2"
